name: PR Build with remaining tests

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build -Dpts.mode=REMAINING_TESTS
      - name: Update status check for Build with remaining tests
        if: always()
        run: |
          status="${{ job.status }}"
          lowercase_status=$(echo $status | tr '[:upper:]' '[:lower:]')
          curl \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data '{
              "state": "'$lowercase_status'",
              "context": "Build With Remaining Tests", 
              "description": "Run PTS remaining tests before merge" 
              }'
